### ISSUE TITLE
UnboundLocalError: local variable 'x' referenced before assignment

### ISSUE THREAD

**Issue by masterwusama** [SayaSS/vits-finetuning#19]
NFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:25<00:00,  2.51s/it]
INFO:checkpoints:====> Epoch: 0
  0%|                                                                                           | 0/10 [00:00<?, ?it/s]INFO:checkpoints:Train Epoch: 1 [0%]
INFO:checkpoints:[2.7146995067596436, 1.8104487657546997, 3.7335586547851562, 20.140308380126953, 1.5783179998397827, 2.673888921737671, 0, 0.00018441474976678928]
DEBUG:matplotlib:matplotlib data path: C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\XXX\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
  0%|                                                                                           | 0/10 [00:18<?, ?it/s]
Traceback (most recent call last):
  File "E:\VITS\vits-finetuning\vits-finetuning\train_ms.py", line 306, in <module>
    main()
  File "E:\VITS\vits-finetuning\vits-finetuning\train_ms.py", line 56, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\VITS\vits-finetuning\vits-finetuning\train_ms.py", line 124, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "E:\VITS\vits-finetuning\vits-finetuning\train_ms.py", line 232, in train_and_evaluate
    evaluate(hps, net_g, eval_loader, writer_eval)
  File "E:\VITS\vits-finetuning\vits-finetuning\train_ms.py", line 265, in evaluate
    y_hat, attn, mask, *_ = generator.module.infer(x, x_lengths, speakers, max_len=1000)
UnboundLocalError: local variable 'x' referenced before assignment

![1679496447059](https://user-images.githubusercontent.com/10389304/226942005-36f39205-242f-4c11-a4cc-67b37bb5e0c6.png)

本地和Colab上都遇到这个问题了，请问是为啥😰

**Comment by masterwusama** [comment]
😅原来是验证集文件没有内容 没事了

**Comment by asao-kanta** [comment]
@masterwusama 
how did you resolve this problem??
i have the same error
