### ISSUE TITLE
 Getting requirements to build wheel ... error

### ISSUE THREAD

**Issue by ReSword** [SayaSS/vits-finetuning#23]
大佬帮帮看看这个问题
本地安装报错
运行环境 windows python 3.7 
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      Traceback (most recent call last):
        File "C:\Users\Seele\.conda\envs\py39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Seele\.conda\envs\py39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Seele\.conda\envs\py39\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Seele\AppData\Local\Temp\pip-build-env-qwqbot8u\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\Seele\AppData\Local\Temp\pip-build-env-qwqbot8u\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\Seele\AppData\Local\Temp\pip-build-env-qwqbot8u\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Seele\AppData\Local\Temp\pip-build-env-qwqbot8u\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "C:\Users\Seele\.conda\envs\py39\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\Seele\.conda\envs\py39\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\Seele\.conda\envs\py39\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by NangenX** [comment]
我也是同样的问题，尝试用3.7.0、3.7、3.8的版本，包括修改跟colab一样的版本，也是这个问题
Cython==0.29.33
librosa==0.8.1
matplotlib==3.5.3
numpy==1.22.4
scipy==1.7.3
tensorboard==2.11.2
torch==1.13.1
torchvision==0.14.1
unidecode
pyopenjtalk
protobuf
tqdm

**Comment by SayaSS** [comment]
你好，需要提供更为详细的错误日志，从目前提供的日志里无法判断出是在安装哪个包时发生的错误

**Comment by ReSword** [comment]
下面是我现在执行的语句顺序（ps：python没接触过，不太熟悉）
(base) PS C:\Users\Seele> cd D:\WorkPlace\Project\AI\VITS\vits-finetuning
(base) PS D:\WorkPlace\Project\AI\VITS\vits-finetuning> conda activate py37
(py37) PS D:\WorkPlace\Project\AI\VITS\vits-finetuning> pip install -r requirements.txt
Collecting Cython
  Using cached Cython-0.29.33-py2.py3-none-any.whl (987 kB)
Collecting librosa==0.8.0
  Using cached librosa-0.8.0.tar.gz (183 kB)
  Preparing metadata (setup.py) ... done
Collecting matplotlib
  Using cached matplotlib-3.5.3-cp37-cp37m-win_amd64.whl (7.2 MB)
Collecting numpy
  Using cached numpy-1.21.6-cp37-cp37m-win_amd64.whl (14.0 MB)
Collecting scipy
  Using cached scipy-1.7.3-cp37-cp37m-win_amd64.whl (34.1 MB)
Collecting tensorboard
  Using cached tensorboard-2.11.2-py3-none-any.whl (6.0 MB)
Collecting torch
  Using cached torch-1.13.1-cp37-cp37m-win_amd64.whl (162.6 MB)
Collecting torchvision
  Using cached torchvision-0.14.1-cp37-cp37m-win_amd64.whl (1.1 MB)
Collecting unidecode
  Using cached Unidecode-1.3.6-py3-none-any.whl (235 kB)
Collecting pyopenjtalk
  Using cached pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      Traceback (most recent call last):
        File "C:\Users\Seele\.conda\envs\py37\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Seele\.conda\envs\py37\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Seele\.conda\envs\py37\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Seele\AppData\Local\Temp\pip-build-env-ylce1_qo\overlay\Lib\site-packages\setuptools\build_meta.py", line 163, in get_requires_for_build_wheel
          config_settings, requirements=['wheel'])
        File "C:\Users\Seele\AppData\Local\Temp\pip-build-env-ylce1_qo\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\Seele\AppData\Local\Temp\pip-build-env-ylce1_qo\overlay\Lib\site-packages\setuptools\build_meta.py", line 268, in run_setup
          self).run_setup(setup_script=setup_script)
        File "C:\Users\Seele\AppData\Local\Temp\pip-build-env-ylce1_qo\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "C:\Users\Seele\.conda\envs\py37\lib\subprocess.py", line 488, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\Seele\.conda\envs\py37\lib\subprocess.py", line 800, in __init__
          restore_signals, start_new_session)
        File "C:\Users\Seele\.conda\envs\py37\lib\subprocess.py", line 1207, in _execute_child
          startupinfo)
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(py37) PS D:\WorkPlace\Project\AI\VITS\vits-finetuning>

**Comment by SayaSS** [comment]
Windows下安装`pyopenjtalk`出错。
这边看到你有使用Anaconda，可以先尝试先`conda install cmake`，再`pip install -r requirements.txt`

或者你可以参考这个视频 https://b23.tv/ecuoe19

**Comment by ReSword** [comment]
应该可以了  我只装了cmake还不够  需要同时再把msvc装上 ，感谢大佬

**Comment by NangenX** [comment]
解决方案
1. conda install cmake
2. 根据视频安装MSVC并配置cmake环境
3. 在pip install -r requirements.txt

**Comment by ReSword** [comment]
不过 我是装了Anaconda这个  流程不一定通用  但如果也遇到这个问题  可以借鉴一下
