### ISSUE TITLE
DataLoader throws IndexError

### ISSUE THREAD

**Issue by ReiFan49** [SayaSS/vits-finetuning#29]
Error happened when loading files right before training the model.

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/vits-tts/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/opt/condapro/vits-tts/train_ms.py", line 124, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/opt/condapro/vits-tts/train_ms.py", line 144, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers) in enumerate(tqdm(train_loader)):
  File "/opt/miniconda3/envs/vits-tts/lib/python3.10/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/opt/miniconda3/envs/vits-tts/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/opt/miniconda3/envs/vits-tts/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/opt/miniconda3/envs/vits-tts/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/opt/miniconda3/envs/vits-tts/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/miniconda3/envs/vits-tts/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/miniconda3/envs/vits-tts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/opt/condapro/vits-tts/data_utils.py", line 256, in __call__
    torch.LongTensor([x[1].size(1) for x in batch]),
  File "/opt/condapro/vits-tts/data_utils.py", line 256, in <listcomp>
    torch.LongTensor([x[1].size(1) for x in batch]),
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

This happened to both models I want to train and the provided Forgotten Rabbit Squadron girl as well. I followed most of the steps in-order from Colab as reference (with modified lines).

GPU: RTX 4090
pyTorch: 2.0.0

Let me know if there are any more information required.

**Comment by SayaSS** [comment]
torch version?

**Comment by ReiFan49** [comment]
```
absl-py==1.4.0
audioread==3.0.0
brotlipy==0.7.0
cachetools==5.3.0
certifi @ file:///croot/certifi_1671487769961/work/certifi
cffi @ file:///croot/cffi_1670423208954/work
chardet==5.1.0
charset-normalizer==3.1.0
contourpy==1.0.7
cryptography @ file:///croot/cryptography_1677533068310/work
cycler==0.11.0
Cython==0.29.34
decorator==5.1.1
filelock @ file:///croot/filelock_1672387128942/work
flit_core @ file:///croot/flit-core_1679397103445/work/source/flit_core
fonttools==4.39.3
gmpy2 @ file:///tmp/build/80754af9/gmpy2_1645455533097/work
google-auth==2.17.2
google-auth-oauthlib==1.0.0
grpcio==1.53.0
idna @ file:///croot/idna_1666125576474/work
Jinja2 @ file:///croot/jinja2_1666908132255/work
joblib==1.2.0
kiwisolver==1.4.4
librosa==0.8.0
llvmlite==0.39.1
Markdown==3.4.3
MarkupSafe==2.1.2
matplotlib==3.7.1
mkl-fft==1.3.1
mkl-random @ file:///home/builder/ci_310/mkl_random_1641843545607/work
mkl-service==2.4.0
mpmath==1.2.1
networkx @ file:///croot/networkx_1678964333703/work
numba==0.56.4
numpy @ file:///croot/numpy_and_numpy_base_1672336185480/work
oauthlib==3.2.2
packaging==23.0
Pillow==9.5.0
platformdirs==3.2.0
pooch==1.7.0
protobuf==4.22.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyopenjtalk==0.3.0
pyOpenSSL @ file:///croot/pyopenssl_1677607685877/work
pyparsing==3.0.9
PySocks @ file:///home/builder/ci_310/pysocks_1640793678128/work
python-dateutil==2.8.2
requests==2.28.2
requests-oauthlib==1.3.1
resampy==0.4.2
rsa==4.9
scikit-learn==1.2.2
scipy==1.10.1
six @ file:///tmp/build/80754af9/six_1644875935023/work
soundfile==0.12.1
sympy @ file:///croot/sympy_1668202399572/work
tensorboard==2.12.1
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
torch==2.0.0
torchaudio==2.0.0
torchvision==0.15.0
tqdm==4.65.0
triton==2.0.0
typing_extensions==4.5.0
Unidecode==1.3.6
urllib3 @ file:///croot/urllib3_1680254681959/work
Werkzeug==2.2.3
```
that one?
Installed torch + cu118
![image](https://user-images.githubusercontent.com/9847780/230701734-841bb78f-47d0-4e54-b148-fe68ab0f7f45.png)
![image](https://user-images.githubusercontent.com/9847780/230704545-c1ea50f3-1ab6-47fe-ad42-9808c317cdba.png)

**Comment by SayaSS** [comment]
Actually, I suggest using the torch version specified in requirements.txt instead of torch2.0...
Or you could try editing line 104 in mel_processing.py like this.
```diff
spec = torch.stft(y, n_fft, hop_length=hop_size, win_length=win_size, window=hann_window[wnsize_dtype_device], center=center, pad_mode='reflect', normalized=False, onesided=True, return_complex=False)
```

**Comment by ReiFan49** [comment]
> Actually, I suggest using the torch version specified in requirements.txt instead of torch2.0...

the (last) image I put on last reply, says `sm89` is unsupported on given `torch 1.12.1` that I've been trying to install back and forth. (Colab Free uses `sm75` which is strangely supported)
~~building from source is a big nightmare because how convoluted the process is...~~

> Or you could try editing line 104 in mel_processing.py like this.
> 
> ```diff
> spec = torch.stft(y, n_fft, hop_length=hop_size, win_length=win_size, window=hann_window[wnsize_dtype_device], center=center, pad_mode='reflect', normalized=False, onesided=True, return_complex=False)
> ```

I've been trying to do both `return_complex=False` and `return_complex=True + view_as_real` but it still returns the same error... most of the files are on pristine state so I don't know which part is defective anymore. Also, I've tried to reinstate the environment (using conda) doesn't change as well.

**Comment by SayaSS** [comment]
Oh sorry, I didn’t notice that there is another place where torch.stft() needs to be modified… You can try git pull and run again.

**Comment by ReiFan49** [comment]
Nope,

![image](https://user-images.githubusercontent.com/9847780/230737302-378335fa-42be-450d-b517-7c938d0fe1c3.png)

I logged this, as it happens on `collate_fn`.
But forcing them to `view_as_real` doesn't really solve the problem 🤔...

**Comment by ReiFan49** [comment]
![image](https://user-images.githubusercontent.com/9847780/230738311-138e3b03-3ac1-4541-b4b6-96b4da2f875e.png)

Looks like I managed to patch it.

On **any collate-ish class**, wrap the batch into a "file global function" or whatever that is global, that performs this
```py
def convert_tensor_batch(batch):
    def check_tensor_value(tensor):
        if not torch.is_tensor(tensor):
            return tensor # not a tensor
        if tensor.is_complex():
            return torch.view_as_real(tensor)
        return tensor
    def check_tensor_tuple(tentup):
        return (type(tentup))(check_tensor_value(tensor) for tensor in tentup)
    return [check_tensor_tuple(tensor) for tensor in batch]
```

This will recreate the tuple-of-4 contents into non-complex returning tuple, if any.

Also for further struggle I'll open other case as this is solved (until committed and closed automatically).

**Comment by ReiFan49** [comment]
Ok, everything is solved by re-instating everything. I think the problem is *the order of installation*.

The way I fixed so far is, *have to sync torch and torchvision* into compatible version.

```
# ... pre python & pip install step here ...

# install base dep of the repo
pip install -r requirements.txt

# install pytorch to fit the GPU
pip install -U torch torchvision --index-url <cuda ver wheel index>
```
