### ISSUE TITLE
No module named 'unidecode'

### ISSUE THREAD

**Issue by Gipers** [SayaSS/vits-finetuning#33]
I was be able to use vits for past 2 days, but recently TensorRT and unidecode are having problem when i do train. Any idea about why this is happen?
Thank you very much

```
2023-04-11 01:31:43.648439: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-11 01:31:44.927418: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/vits-finetuning/train_ms.py", line 24, in <module>
    from data_utils import (
  File "/content/vits-finetuning/data_utils.py", line 11, in <module>
    from text import text_to_sequence, cleaned_text_to_sequence
  File "/content/vits-finetuning/text/__init__.py", line 2, in <module>
    from text import cleaners
  File "/content/vits-finetuning/text/cleaners.py", line 2, in <module>
    from text.japanese import japanese_to_romaji_with_accent
  File "/content/vits-finetuning/text/japanese.py", line 2, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'
```

**Comment by SayaSS** [comment]
Fixed, caused by Colab 's forward-break things
