### ISSUE TITLE
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now

### ISSUE THREAD

**Issue by boypjm998** [SayaSS/vits-finetuning#42]
您好，我之前好久没有跑这个代码了，今天试了一下，发现无论如何都报这个错误，我之前运行的时候，无论这个音频文件有多长，都没有出现过这个问题。但是我这次把它们都切割到8s以内，batchSize试着改了一下也一直是报这些问题。想麻烦问一下这种情况是怎么回事呢？

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/vits-finetuning/train_ms.py", line 124, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/content/vits-finetuning/train_ms.py", line 144, in train_and_evaluate
    for batch_idx, (x, x_lengths, spec, spec_lengths, y, y_lengths, speakers) in enumerate(tqdm(train_loader)):
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1313, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.10/dist-packages/torch/_utils.py", line 543, in reraise
    raise exception
NotImplementedError: Caught NotImplementedError in DataLoader worker process 7.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/vits-finetuning/data_utils.py", line 236, in __getitem__
    return self.get_audio_text_speaker_pair(self.audiopaths_sid_text[index])
  File "/content/vits-finetuning/data_utils.py", line 199, in get_audio_text_speaker_pair
    spec, wav = self.get_audio(audiopath)
  File "/content/vits-finetuning/data_utils.py", line 214, in get_audio
    spec = spectrogram_torch(audio_norm, self.filter_length,
  File "/content/vits-finetuning/mel_processing.py", line 63, in spectrogram_torch
    y = torch.nn.functional.pad(y.unsqueeze(1), (int((n_fft-hop_size)/2), int((n_fft-hop_size)/2)), mode='reflect')
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now

**Comment by biubiu111** [comment]
您好，请问您解决了吗？是如何解决的？
